server:
  port: 8089

spring:
  application:
    name: LAKESIDE-HOTEL
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lakeSide_hotel_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true